[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "GrwLqfab7NjYCwxgxDKwBbxhvkMAeQzc1MBohDk6mdqk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/akileus/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
